### ISSUE TITLE
remark@next (13)

### ISSUE THREAD

**Issue by wooorm** [unlight/remark-package-dependencies#1]
Hi!

remark is switching to a new parser internally ([`remarkjs/remark#536`](https://github.com/remarkjs/remark/pull/536)).
It seems this plugin should be fine (although tables will be moved to `remark-gfm`), however, it would be good to check that in the future (there is `13.0.0-alpha.0` published now, and one or two more will come before the release)

**Comment by unlight** [comment]
Test with `13.0.0-alpha.0` failed:
```
Cannot handle unknown node `table`
```

**Comment by wooorm** [comment]
See my comment about tables, remark-gfm will 'em, and be released soon!
