### ISSUE TITLE
Releasing 2.0.0

### ISSUE THREAD

**Issue by gracegoo-stripe** [unlight/remark-package-dependencies#2]
Hello, I am trying to upgrade remark to 13.0.0 but it looks like the 1.1.1 versions are only compatible with <= 12. 
```
npm ERR! Could not resolve dependency:
npm ERR! peer remark@">=10 <=12" from remark-package-dependencies@1.1.1
npm ERR! node_modules/remark-package-dependencies
npm ERR!   dev remark-package-dependencies@"^1.1.1" from the root project
```

I see that there is a tag for 2.0.0 that is compatible with v13 of remark, will that be released any time soon?

**Comment by unlight** [comment]
It should be available on npm using next channel
npm i remark-package-dependencies@next

I will publish to default channel today

**Comment by gracegoo-stripe** [comment]
Thanks for the quick response @unlight ! I'm able to upgrade but getting this error when running our script:
```
Error: Cannot find module '/Users/gracegoo/stripe/vscode-stripe/node_modules/remark-package-dependencies/index.js'. Please verify that the package.json has a valid "main" entry
```

**Comment by unlight** [comment]
Oh. Looks like something wrong with CI configuration. I'll check.

**Comment by gracegoo-stripe** [comment]
Thank you so much for the quick fix!
